// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALgswb6LeBoGQjf9QEYFb9vyL1z0yx4zE',
    appId: '1:736097279934:web:4757c2504309f1e82ea3ef',
    messagingSenderId: '736097279934',
    projectId: 'planetoids-nuhro',
    authDomain: 'planetoids-nuhro.firebaseapp.com',
    storageBucket: 'planetoids-nuhro.appspot.com',
    measurementId: 'G-R0SMRW36LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxcLOxzLkBsW5FRvJoC6WiL4qBLe8bQM',
    appId: '1:736097279934:android:59f1a450cf334b352ea3ef',
    messagingSenderId: '736097279934',
    projectId: 'planetoids-nuhro',
    storageBucket: 'planetoids-nuhro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFLhc1bgn8yJ2zMxd3odZG-aIzZvVYME',
    appId: '1:736097279934:ios:e62e360f3c21583c2ea3ef',
    messagingSenderId: '736097279934',
    projectId: 'planetoids-nuhro',
    storageBucket: 'planetoids-nuhro.appspot.com',
    iosBundleId: 'com.nuhro.planetoidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFLhc1bgn8yJ2zMxd3odZG-aIzZvVYME',
    appId: '1:736097279934:ios:e62e360f3c21583c2ea3ef',
    messagingSenderId: '736097279934',
    projectId: 'planetoids-nuhro',
    storageBucket: 'planetoids-nuhro.appspot.com',
    iosBundleId: 'com.nuhro.planetoidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALgswb6LeBoGQjf9QEYFb9vyL1z0yx4zE',
    appId: '1:736097279934:web:24393645a495919f2ea3ef',
    messagingSenderId: '736097279934',
    projectId: 'planetoids-nuhro',
    authDomain: 'planetoids-nuhro.firebaseapp.com',
    storageBucket: 'planetoids-nuhro.appspot.com',
    measurementId: 'G-DYR27ZTDGQ',
  );
}
